GET http://localhost:8080/users HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ3MTRmYzUzLWRhMDQtNGExOC1hNmE1LTFhZmU0MTVhMzM2OCIsImVuYWJsZSI6dHJ1ZSwibG9naW4iOiJqb2FvIiwidHlwZSI6IlQiLCJpYXQiOjE3MDQ4NDI4MjUsImV4cCI6MTcwNDkyOTIyNX0._91B-YL798uOk4Qcc4DZ8dOskWUHyvFL07NkAgo1xkg
