GET http://localhost:8080/assessments HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI3OGM2ZjI2LTlhNzItNGZjZC1iN2I4LWNjMGZiNTI3ZGU1NCIsImVuYWJsZSI6dHJ1ZSwibG9naW4iOiJqb2FvIiwidHlwZSI6IlQiLCJpYXQiOjE3MDI5NDg5NDEsImV4cCI6MTcwMzAzNTM0MX0.Q9VGPaNmB_eZfqMWqu8L-5_vf9gWV8EkHAL6uTc8jh0

